version: 2
jobs:
  build:

    working_directory: ~/repo

    docker:
      - image: circleci/openjdk:8-jdk

    steps:

      - checkout

      - restore_cache:
          key: v1-dependencies-{{ checksum "parent-pom/pom.xml" }}

      - run: mvn dependency:go-offline -f parent-pom/pom.xml

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "parent-pom/pom.xml" }}

      - run:
          command: |
                   mvn install -f parent-pom/pom.xml
                   mvn install -f test-tools/pom.xml
                   mvn test -f project-archetype/pom.xml
                   mvn test -f project-myairline/pom.xml
