name: CI

on:
  push:
    branches:
      - 'main'
      - 'feature/pipeline-deployment'
  pull_request:
    types: [ opened ]


jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Set Environment Variables
        id: env-setup
        run: |
          echo "grp=com.profile" >> $GITHUB_OUTPUT
          echo "ART=demo" >> $GITHUB_STATE
          echo "VER=1.0.0" >> $GITHUB_STATE
      - name: print local vars
        run: |
          echo "group: ${{ steps.env-setup.outputs.grp }} EOL"
          # echo "GRP2=${{ env.GRP }}" >> $GITHUB_OUTPUT

  image:
    needs: init
    runs-on: ubuntu-latest
    steps:
      - name: Display DIM Variable
        run: |
          echo "group: ${{ steps.env-setup.outputs.grp }} EOL"
