name: CI

on:
  push:
    branches:
      - 'main'
      - 'feature/pipeline-deployment'
  pull_request:
    types: [ opened ]


jobs:
  init:
    runs-on: ubuntu-latest
    outputs: 
      group_id: ${{ steps.env_setup.outputs.group }}
      artifact_id: ${{ steps.env_setup.outputs.artifact }}
      version: ${{ steps.env_setup.outputs.version }}
    steps:
      - id: env_setup
        name: Set Environment Variables
        run: |
          echo "group=com.profile" >> $GITHUB_OUTPUT
          echo "artifact=demo" >> $GITHUB_OUTPUT
          echo "version=1.0.0" >> $GITHUB_OUTPUT
      - name: print local vars
        run: |
          echo "group: ${{ steps.env_setup.outputs.grp }} EOL"
          # echo "GRP2=${{ env.GRP }}" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: init
    steps:
      - env:
          GROUP_ID: ${{needs.init.outputs.group_id}}
          ARTIFACT_ID: ${{needs.init.outputs.artifact_id}}
          VERSION: ${{needs.init.outputs.version}}
        run: |
          echo "access var"
          echo "$GROUP_ID.$ARTIFACT_ID:$VERSION EOL"