name: CI

on:
  push:
    branches:
      - 'main'
      - 'feature/pipeline-deployment'
  pull_request:
    types: [ opened ]


jobs:
  init:
    runs-on: ubuntu-latest
    outputs: 
      o1: ${{ steps.env_setup.outputs.art }}
    steps:
      - id: env_setup
        name: Set Environment Variables
        run: |
          echo "grp=com.profile" >> $GITHUB_OUTPUT
          echo "art=demo" >> $GITHUB_OUTPUT
          echo "VER=1.0.0"
      - name: print local vars
        run: |
          echo "group: ${{ steps.env_setup.outputs.grp }} EOL"
          # echo "GRP2=${{ env.GRP }}" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: init
    steps:
      - env:
          OUT1: ${{needs.init.outputs.o1}}
        run: |
          echo "access var"
          echo "$OUT1 EOL"