name: CI

on:
  push:
    branches:
      - 'main'
      - 'feature/pipeline-deployment'
  pull_request:
    types: [ opened ]


jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Set Environment Variables
        run: |
          echo "GRP=com.profile" >> $GITHUB_STATE
          echo "ART=demo" >> $GITHUB_STATE
          echo "VER=1.0.0" >> $GITHUB_STATE
      - name: print local vars
        run: |
          echo "group: ${{ env.GRP }}"
          echo "GRP2=${{ env.GRP }}" >> $GITHUB_OUTPUT

  image:
    needs: init
    runs-on: ubuntu-latest
    steps:
      - name: Display DIM Variable
        run: |
          echo "Using final GRP2: ${{ steps.init.outputs.GRP2 }}"
