name: CI

on:
  push:
    branches:
      - 'main'
      - 'feature/pipeline-deployment'
  pull_request:
    types: [ opened ]

env:
  DOCKER_IMAGE: butcherless/sibyplay:1.0.4

jobs:

  init:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    outputs:
      artifact_id: ${{ steps.my-init.outputs.artifact_id }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: set environment variables
        id: my-init
        run: |
          echo "artifact_id=$(./mvnw help:evaluate -Dexpression=project.groupId -q -DforceStdout)" >> "${GITHUB_OUTPUT}"

  build:
    needs: init
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: compile
        run: ./mvnw -V validate

  push-image:
    needs: init
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: check-outputs
        run: |
          echo "artifact_id=${{ needs.init.outputs.artifact_id }} EOL"
      - name: build-image
        run: ./mvnw spring-boot:build-image -Dspring-boot.build-image.imageName=$DOCKER_IMAGE   
      - name: docker-login
        run: echo ${{secrets.DOCKER_PASSWORD}} | docker login --username ${{secrets.DOCKER_USERNAME}} --password-stdin
      - name: docker-list-images
        run: docker images
      - name: docker-push
        run: docker push $DOCKER_IMAGE
    

  deploy-image:
    needs: push-image
    runs-on: ubuntu-22.04
    #container: google/cloud-sdk

    steps:
      - name: gcloud-cli-version
        run: gcloud --version
      - name: environment 
        run: echo "username $DOCKER_USERNAME - variable, $GITHUB_ACTION - action ${{secrets.DOCKER_USERNAME}} "
