name: CI

on:
  push:
    branches:
      - 'main'
      - 'feature/pipeline-deployment'
  pull_request:
    types: [ opened ]

jobs:

  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: compile
        run: ./mvnw -V validate

  push-image:
    runs-on: ubuntu-22.04
    #container: docker:20.10.16

    steps:
      - name: os-version
        run: uname -a
      - name: docker-version
        run: docker push --help

  deploy-image:
    runs-on: ubuntu-22.04
    #container: google/cloud-sdk

    steps:
      - name: gcloud-cli-version
        run: gcloud --version
      - name: environment 
        run: echo "username $DOCKER_USERNAME variable"
