name: CI

on:
  push:
    branches:
      - 'master'
  pull_request:
    types: [ opened ]

jobs:

  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
            distribution: 'zulu'
            java-version: '21'
      - name: check versions
        run: ./mvnw -v
      - name: compile
        run: ./mvnw compile
      - name: test
        run: ./mvnw test
      - name: package
        run: ./mvnw package
