name: CI

on:
  push:
    branches:
      - 'main'
      - 'feature/pipeline-deployment'
  pull_request:
    types: [ opened ]


jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variables
        run: |
          echo "GRP=com.profile" >> $GITHUB_ENV
          echo "ART=demo" >> $GITHUB_ENV
          echo "VER=1.0.0" >> $GITHUB_ENV    

  image:
    needs: init  # Ensure init job runs first
    runs-on: ubuntu-latest
    steps:
      - name: Create DIM variable
        run: |
          echo "DIM=${{ env.GRP }}.${{ env.ART }}.${{ env.VER }}" >> $GITHUB_ENV

      - name: Use DIM variable
        run: |
          echo ${{ env.DIM }}  # Access and use the DIM variable
          # ... other steps that use ${{ env.DIM }}
