name: CI

on:
  push:
    branches:
      - 'main'
      - 'feature/pipeline-deployment'
  pull_request:
    types: [ opened ]

env:
  DOCKER_IMAGE: butcherless/sibyplay:1.0.4


jobs:
  set-global-variable:
    runs-on: ubuntu-latest
    steps:
      - name: Set global variable
        run: echo "MY_VAR=1234" >> $GITHUB_ENV
        shell: bash

      - name: access var
        run: |
          echo "my var: $MY_VAR eol"

  use-global-variable:
    needs: set-global-variable
    runs-on: ubuntu-latest
    steps:
      - name: Use global variable
        run: |
          echo "Global variable MY_VAR: $MY_VAR"
  