name: Java Setup

on:
  # Inherit triggers from the main workflow (optional)

jobs:
  # Empty jobs section, no steps here

steps:
  - uses: actions/checkout@v3
  - name: Setup Java JDK 17
    uses: actions/setup-java@v3
    with:
      java-version: 17
  - name: Cache Maven packages
    uses: actions/cache@v3
    with:
      path: ~/.m2/repository
      key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
      restore-keys: |
        ${{ runner.os }}-maven-
